---
name: Publish to Cloudflare Pages

on:
  push:
    branches: [master]

env:
  PROJECT_NAME: monkeytype
  BUILD_DIR: frontend/dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
      - name: "Install dependencies"
        run: |
          npm ci
          npm install @rollup/rollup-linux-x64-gnu
      - name: "Build"
        run: |
          export ENV BACKEND_URL=###MONKEYTYPE_BACKENDURL###
          export RECAPTCHA_SITE_KEY=###RECAPTCHA_SITE_KEY###
          cp docker/frontend/firebase-config-live.ts frontend/src/ts/constants/firebase-config.ts
          cp docker/frontend/firebase-config-live.ts frontend/src/ts/constants/firebase-config-live.ts
          npm run build-fe
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
